name: 'Trigger ADO Image Builder'
description: 'Triggers the run of the ADO image builder backend'
inputs:
  oidc-token:
    description: The JWT token to authenticate against Azure DevOps image builder backend
    required: true
  ado-token:
    description: The personal access token to authenticate against Azure DevOps API
    required: true
  image-name:
    description: Name of the build image
    required: true
  context:
    description: Build context to build container from
    required: false
    default: .
  dockerfile:
    description: Path to the dockerfile used to build docker image
    required: false
    default: Dockerfile
  dry-run:
    description: Prevent actual triggering the image builder
    required: false
    default: false
 runs:
  using: 'docker'
  image: europe-docker.pkg.dev/kyma-project/prod/image-builder:v20240402-5a67f2a8
  args:
    - "--name=${{{ inputs.image-name }}}"
    - "--context=${{ inputs.context }}"
    - "--dockerfile=${{ inputs.dockerfile }}"
    - "--build-in-ado=true"