name: build-image-detector
on:
  # This workflow is triggered by workflow controller.
  workflow_call:

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: image-detector
      dockerfile: cmd/image-detector/Dockerfile
      context: .
      build-engine: buildx
      platforms: |
        linux/amd64