name: pull-build-image-autobumper
on:
  push:
    branches:
      - main
    paths:
      - 'cmd/image-autobumper/**'
      - 'go.mod'
      - 'go.sum'
      - "pkg/**"
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - 'cmd/image-autobumper/**'
      - "go.mod"
      - "go.sum"
      - "pkg/**"
  workflow_dispatch: {}

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: image-autobumper
      dockerfile: cmd/image-autobumper/Dockerfile
      context: .
  print-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Print image
        run: echo "Image built ${{ needs.build-image.outputs.images }}"