name: build-github-com-webhook-gateway
on:
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - "cmd/cloud-run/github-webhook-gateway/*.go"
      - "cmd/cloud-run/github-webhook-gateway/Dockerfile"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
  push:
    branches:
      - main
    paths:
      - "cmd/cloud-run/gh_com_webhook_gw/*.go"
      - "cmd/cloud-run/gh_com_webhook_gw/Dockerfile"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
  workflow_dispatch: {}

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: ./.github/workflows/image-builder.yml
    with:
      name: github-com-webhook-gateway
      dockerfile: cmd/cloud-run/gh_com_webhook_gw/Dockerfile
      context: .
  print-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Print image
        run: echo "Image built ${{ needs.build-image.outputs.images }}"
