name: code-checks-python

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/code-checks-python.yml'
      - '**/*.py'
      - '**/requirements.txt'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate matrix
        id: set-matrix
        run: |
          # Find all directories containing .py files
          py_dirs=$(find . -type f -name "*.py" -exec dirname {} \; | sort -u)

          root_dirs=""
          for dir in $py_dirs; do
            parent=$(dirname "$dir")

            # If parent does not contain any .py files, consider as root dir
            if ! find "$parent" -maxdepth 1 -type f -name "*.py" | grep -q .; then
              # Remove leading './' if present
              clean_dir="${dir#./}"
              root_dirs="$root_dirs $clean_dir"
            fi

          done

          # Remove leading/trailing whitespace
          root_dirs=$(echo $root_dirs | xargs)
          echo "Found applications directories: $root_dirs"

          matrix="$(echo $root_dirs | jq -Rsc '. | split(" ") | {app: .}')"
          echo "Genrated matrix: $matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  unittest:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
         
          # Install dependencies if requirements.txt exists
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
        working-directory: ${{ matrix.app }}
      
      - name: Run unit tests
        run: |
          source venv/bin/activate
          python3 -m unittest discover
        working-directory: ${{ matrix.app }}
  
  lint:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

          # Install dependencies if requirements.txt exists
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

          pip install pylint
        working-directory: ${{ matrix.app }}

      - name: Analysing the code with pylint
        run: |
          source venv/bin/activate
          pylint ./**/*.py
        working-directory: ${{ matrix.app }}
