name: lint-python

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint-python.yml'
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint ./**/*.py
