name: Get OIDC Token Workflow

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/get-oidc-token.yml"
      - ".github/workflows/reusable-workflow.yml"
      - ".github/actions/expose-jwt-action/**"

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml # Usage: kyma-project/test-infra/.github/workflows/reusable-workflow.yml@main
    with:
      name: test-infra/ginkgo
      dockerfile: prow/images/ginkgo/Dockerfile
      context: .
