name: Test actions created for image builder

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
  workflow_dispatch:


jobs:
  call_reusable_workflow:
   uses: ./.github/workflows/reusable-workflow.yml
    