name: test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

env:
  GITLEAKS_VERSION: 8.18.2

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: cat $GITHUB_EVENT_PATH
      - run: env
