name: Get OIDC Token Workflow

on: 
  workflow_dispatch:
  pull_request_target:
   types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  call_reusable_workflow:
   uses: kyma-project/test-infra/.github/workflows/reusable-workflow.yml@main
  get_env:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: cat $GITHUB_EVENT_PATH
