name: Get OIDC Token Workflow

on: 
  workflow_dispatch:
  push:
  pull_request_target:
   types: [ opened, edited, synchronize, reopened, ready_for_review ]

env:
  GITHUB_EVENT_PATH: "test"

jobs:
  get_env:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: cat $GITHUB_EVENT_PATH
  call_reusable_workflow:
   uses: ./.github/workflows/reusable-workflow.yml
