name: workflow-controller-build-2

on:
  pull_request_target: 
    types: [opened, synchronize, reopened, ready_for_review]
  push:
  merge_group: 

jobs:
  detect-changed-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.pathFilters.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: pathFilters
        with:
          filters: controller-filters.yaml

  build-rotate-service-account-keys:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-rotate-service-account-keys-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflowsbuild-rotate-service-account-keys.yml@refs/heads/main
  
  build-service-account-keys-cleaner-filter:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-service-account-keys-cleaner-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflowsbuild-service-account-keys-cleaner.yml@refs/heads/main

  build-signify-secret-rotator:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-signify-secret-rotator-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflowsbuild-signify-secret-rotator.yml@refs/heads/main

  build-slack-message-sender:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-slack-message-sender-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflowsbuild-slack-message-sender.yml@refs/heads/main

  build-usersmapchecker:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'build-usersmapchecker-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflowsbuild-usersmapchecker.yml@refs/heads/main

  # !WARNING: This workflow counts as 10 separate jobs!
  buildx-images:
    if: ${{ contains(needs.detect-changed-files.outputs.files, 'buildx-images-filter') }}
    needs: detect-changed-files
    uses: kyma-project/test-infra/.github/workflowsbuildx-images.yml@refs/heads/main